const $=s=>document.querySelector(s), api=window.API_BASE_URL;
let state={page:'home',games:[],game:null,products:[],user:null,telegram_id:localStorage.getItem('telegram_id')||'demo-user',name:localStorage.getItem('name')||'Demo User'};
const money=n=>new Intl.NumberFormat('uz-UZ').format(n)+' so‘m';
async function get(path){const r=await fetch(api+path);if(!r.ok)throw Error(await r.text());return r.json()}
async function post(path,body,opts={}){const r=await fetch(api+path,{method:'POST',headers:opts.headers||{},body:opts.body||JSON.stringify(body),...(opts.body?{}:{headers:{'Content-Type':'application/json'}})});if(!r.ok)throw Error(await r.text());return r.json()}
async function ensureUser(){try{state.user=await post('/users',{telegram_id:state.telegram_id,name:state.name,referral_code:new URLSearchParams(location.search).get('ref')})}catch(e){console.error(e)}}
function header(title,sub=''){ $('#title').textContent=title;$('#subtitle').textContent=sub;$('#balance').textContent=money(state.user?.balance||0)+' ＋';$('#back').classList.toggle('hidden',!state.game)}
async function home(){state.game=null;state.games=await get('/games');header('Game Top-Up','O‘yinlar');$('#content').innerHTML='<div class="grid">'+state.games.map(g=>`<article class="game" onclick="openGame(${g.id})"><img src="${g.image}" onerror="this.style.display=\'none\'"><div><b>${g.name}</b></div></article>`).join('')+'</div>'}
async function openGame(id){state.game=state.games.find(x=>x.id===id);state.products=await get('/games/'+id+'/products');header(state.game.name,'Paketlar va obunalar');renderProducts()}
function renderProducts(){const cats=['Hammasi',...new Set(state.products.map(p=>p.category))];$('#content').innerHTML='<div class="tabs">'+cats.map((c,i)=>`<button class="${i===0?'active':''}" onclick="filterProducts(this,'${c}')">${c}</button>`).join('')+'</div><div id="products" class="grid"></div>';drawProducts('Hammasi')}
function drawProducts(cat){const ps=cat==='Hammasi'?state.products:state.products.filter(p=>p.category===cat);$('#products').innerHTML=ps.map(p=>`<article class="product" onclick="buy(${p.id})"><img src="${p.image}"><div><b>${p.name}</b><div class="price">${money(p.price)}</div></div></article>`).join('')||'<div class="panel muted">Hozircha mahsulot yo‘q.</div>'}
function filterProducts(el,cat){document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));el.classList.add('active');drawProducts(cat)}
function buy(id){const p=state.products.find(x=>x.id===id);const isSub=p.product_type==='subscription';$('#modal').classList.remove('hidden');$('#modal').innerHTML=`<div><h2>${p.name}</h2><p class="price">${money(p.price)}</p><div class="field"><label>Player ID / UID / Email</label><input id="account1" placeholder="Kerakli ma’lumot"></div><div class="field"><label>Server (kerak bo‘lsa)</label><input id="server"></div>${isSub?'<p class="muted">Referal chegirmasi mavjud bo‘lsa avtomatik qo‘llanadi.</p>':''}<button class="primary" onclick="submitOrder(${p.id})">Xarid qilish</button></div>`}
async function submitOrder(id){try{const r=await post('/orders',{telegram_id:state.telegram_id,product_id:id,account_data:{primary:$('#account1').value,server:$('#server').value}});alert('Buyurtma #'+r.id+' qabul qilindi.');$('#modal').classList.add('hidden');state.user=await get('/me?telegram_id='+encodeURIComponent(state.telegram_id));header(state.game.name,'Paketlar va obunalar')}catch(e){alert('Xatolik: '+e.message)}}
async function orders(){header('Xaridlarim','Barcha buyurtmalar');const os=await get('/orders?telegram_id='+encodeURIComponent(state.telegram_id));$('#content').innerHTML='<div class="grid">'+os.map(o=>`<div class="panel"><b>#${o.id}</b><p>${o.status}</p><p>${money(o.price)}</p><small>${new Date(o.created_at).toLocaleString('uz-UZ')}</small></div>`).join('')+'</div>'}
async function profile(){header('Profil','Hisob');const u=await get('/me?telegram_id='+encodeURIComponent(state.telegram_id));state.user=u;$('#content').innerHTML=`<div class="panel"><h2>${u.name}</h2><p>Balans: <b>${money(u.balance)}</b></p><p>Referal: <code>${u.referral_code}</code></p><p>Chegirma ishlatilgan: ${u.discount_uses}/${u.discount_limit}</p><button class="primary" onclick="deposit()">💰 Balansni to‘ldirish</button></div>`}
function deposit(){$('#modal').classList.remove('hidden');$('#modal').innerHTML=`<div><h2>💰 Balansni to‘ldirish</h2><p>Karta: <b>Admin orqali sozlanadi</b></p><p>Chekni to‘lovdan keyin yuboring.</p><div class="field"><label>Summa</label><input id="depAmount" type="number"></div><div class="field"><label>Chek</label><input id="receipt" type="file" accept="image/*"></div><button class="primary" onclick="sendDeposit()">📸 Chekni yuborish</button></div>`}
async function sendDeposit(){const fd=new FormData();fd.append('telegram_id',state.telegram_id);fd.append('amount',$('#depAmount').value);fd.append('receipt',$('#receipt').files[0]);try{await post('/deposits',{}, {body:fd});alert('Chek adminga yuborildi.');$('#modal').classList.add('hidden')}catch(e){alert(e.message)}}
$('#back').onclick=home;document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>({home,orders,profile}[b.dataset.page])());
(async()=>{await ensureUser();await home()})()
